name: CopyrightYear
version: '1.0'
description: 'Format copyright year to display in footer.'
url: https://github.com/gabrieltakacs/statamic-copyright-year
developer: 'Ing. Gabriel Takács'
developer_url: 'https://www.takacs-it.com'
